apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bj0ofyzn1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bj0ofyzn1-go 
  name: bj0ofyzn1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bj0ofyzn1-go 
